firstsite/firstsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstsiteapp.urls', namespace='firstsite')),
    path('/users', include('userapp.urls', namespace='users'))
]

if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

firstsite/firstsiteapp/urls.py
from django.urls import path
from firstsiteapp import views
from .views import BookList
from django.conf.urls import url


app_name = 'firstsiteapp'

urlpatterns = [
    path('', BookList.as_view(),  name='index'),
   # path('', views.main_view, name='index'),
    path('create/', views.create_book, name='create_link'),
    path('db/', views.db, name='db_link'),
    path('book/<int:id>/', views.book, name='book'),
    path('cat-list', views.CatListView.as_view(), name='cat_list'),
    path('cat-create/', views.CatCreateView.as_view(), name='cat_create'),
    path('cat-edit/<int:pk>/', views.CatEditView.as_view(), name='cat_edit'),
    path('cat-delete/<int:pk>/', views.CatDeleteView.as_view(), name='cat_delete'),
    path('year-list', views.YearListView.as_view(), name='year_list'),
    path('year-create/', views.YearCreateView.as_view(), name='year_create'),
    path('year-edit/<int:pk>/', views.YearEditView.as_view(), name='year_edit'),
    path('year-delete/<int:pk>/', views.YearDeleteView.as_view(), name='year_delete')
    ]

firstsite/userapp/urls.py
from django.urls import path
from userapp import views
from django.contrib.auth.views import LogoutView


from django.conf.urls import url


app_name = 'userapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(),  name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register')
]

firstsite/firstsiteapp/models.py
from django.db import models
from userapp.models import SiteUser
from django.db.models import F


# models.DataField
    # models.DateTimeField
    # models.TimeField
    # models.IntegerField
    # models.PositiveIntegerField
    # models.PositiveSmallIntegerField
    # models.FloatField
    # models.DecimalField
    # models.BooleanField
    # models.BinaryField
    # models.ImageField
    # models.FileField
    # models.URLField
    # models.EmailField

class ActiveManager(models.Manager):

    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)


class IsActiveMixin(models.Model):
    objects = models.Manager()
    active_objects = ActiveManager()
    is_active = models.BooleanField(default=False)

    class Meta:
        abstract = True

class UpdatedObjectsManager(models.Manager):

    def get_queryset(self):
        all_objects = super().get_queryset()
        # Дата обновления не равна дата содания F - запрос
        return all_objects.filter(update=F('create'))

class Year(models.Model):
    name = models.CharField(max_length=4, unique=True)
   # description = models.CharField(max_length=4, unique=True)

    def __str__(self):
        return self.name



class Category(models.Model):
    name = models.CharField(max_length=16, unique=True)
    description = models.TextField(blank=True)
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Book(models.Model):
    create = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=32, unique=False)
    description = models.TextField(blank=False)
    link = models.URLField(max_length=128, unique=False)
    authors = models.CharField(max_length=16, unique=False)
    language = models.CharField(max_length=20, unique=False)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)


    def __str__(self):
        return self.name


class CoreObject(models.Model):
    name = models.CharField(max_length=32)

firstsite/firstsiteapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.Form):
    name = forms.CharField(label='Название книги',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))
    authors = forms.CharField(label='Автор(ы)')
    language = forms.CharField(label='Язык')
    link = forms.URLField(label='Ссылка')

    class Meta:
        model = Book
        exclude = ('user',)

firstsite/firstsiteapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Book, Category, Year
from django.urls import reverse, reverse_lazy
from .forms import BookForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin


def main_view(request):
    books = Book.objects.all()[:15]
    return render(request, 'firstsiteapp/index.html', context={'books': books})



def create_book(request):
    if request.method == 'GET':
        form = BookForm()
        return render(request, 'firstsiteapp/create.html', context={'form': form})
    else:
        form = BookForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            link = form.cleaned_data['link']
            return HttpResponseRedirect(reverse('firstsite:index'))
        else:
             return render(request, 'firstsiteapp/create.html', context={'form': form})


def book(request, id):
    book = get_object_or_404(Book, id=id)
    return render(request, 'firstsiteapp/book.html', context={'book': book})

@user_passes_test(lambda u: u.is_superuser)
def db(request):
    return render(request, 'firstsiteapp/db.html')


class BookList(ListView):
    model = Book
    paginate_by = 10



class NameContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):

        context = super().get_context_data(*args, **kwargs)
        return context


class CatListView(ListView, NameContextMixin):
    model = Category
    template_name = 'firstsiteapp/cat_list.html'
    context_object_name = 'categories'

    def get_queryset(self):

        return Category.objects.all()


class CatCreateView(CreateView, NameContextMixin):
    fields = '__all__'
    model = Category
    success_url = reverse_lazy('firstsite:cat_list')
    template_name = 'firstsiteapp/cat_create.html'

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super().form_valid(form)


class CatEditView(UpdateView):
    fields = '__all__'
    model = Category
    success_url = reverse_lazy('firstsite:cat_list')
    template_name = 'firstsiteapp/cat_create.html'


class CatDeleteView(DeleteView):
    template_name = 'firstsiteapp/cat_delete.html'
    model = Category
    success_url = reverse_lazy('firstsite:cat_list')


class CatListView(ListView, NameContextMixin):
    model = Category
    template_name = 'firstsiteapp/cat_list.html'
    context_object_name = 'categories'

    def get_queryset(self):

        return Category.objects.all()


class YearCreateView(CreateView, NameContextMixin):
    fields = '__all__'
    model = Year
    success_url = reverse_lazy('firstsite:year_list')
    template_name = 'firstsiteapp/year_create.html'

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super().form_valid(form)


class YearEditView(UpdateView):
    fields = '__all__'
    model = Year
    success_url = reverse_lazy('firstsite:year_list')
    template_name = 'firstsiteapp/year_create.html'


class YearDeleteView(DeleteView):
    template_name = 'firstsiteapp/year_delete.html'
    model = Year
    success_url = reverse_lazy('firstsite:year_list')


class YearListView(ListView, NameContextMixin):
    model = Year
    template_name = 'firstsiteapp/year_list.html'
    context_object_name = 'years'

    def get_queryset(self):
        return Year.objects.all().order_by('-name')

firstsite/firstsiteapp/templates/firstsiteapp/book.html
{% extends "base.html" %}
{% block title %}
  {{book.name}}
{% endblock %}

{% block content %}

  <!-- Post Content -->

    <h1 class="post-preview">
        {{book.name}}
    </h1>
    <p> {{book.authors}} </p>
    <p> {{book.language}} </p>
    <p> {{book.category}} </p>
    </p> {{book.link}} </p>

{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/book_list.html
{% extends "base.html" %}
{% block title %}{% endblock %}

{% block content %}

    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in book_list %}
          <div class="post-preview">
            <a href="{% url 'firstsite:book' id=item.id %}">
              <h1 class="post-title">
                {{ item.name }}
              </h1>
              <h2 class="post-subtitle">
                {{ item.authors }}
              </h2>
              <h3 class="post-subtitle">
                {{ item.category }}
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">User</a>
              {{item.create}}</p>
          </div>
        {% endfor %}
        <hr>
        <!-- Pager -->
      </div>
    </div>
{% block pagination %}
  {% if is_paginated %}

      <div class="clearfix">
          <span class="btn btn-primary float-right">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/cat_create.html
{% extends "base.html" %}
{% block title %}
{% endblock %}

  {% block content %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Укажите название категории</p>
        <form method="post" id="createForm">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>

        </form>
      </div>
    </div>

  {% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/cat_delete.html
{% extends "base.html" %}

{% block title %}
{{object.name}}
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        Удалить категорию "{{object.name}}"?
    </div>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
    </form>
</div>
{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/cat_edit.html
{% extends "base.html" %}

{% block title %}
    Редактирование элемента
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/cat_list.html
{% extends "base.html" %}
{% block title %}
    изменить элемент
{% endblock %}

{% block content %}

    <div class="row">
    <h1>Список категорий</h1>
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in categories %}
          <div>
             <b>  {{ item.name }} </b>
             <a href="{% url 'firstsite:cat_edit' pk=item.pk %}">
                     &nbsp&nbsp&nbsp ️изменить &nbsp
                </a>
                <a href="{% url 'firstsite:cat_delete' pk=item.pk %}">
                     &nbsp&nbsp&nbsp  удалить  &nbsp
                </a>
          </div>
        {% endfor %}
      </div>
    </div>


{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/create.html
{% extends "base.html" %}
{% block title %}
{% endblock %}

  {% block content %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Укажите название и ссылку для новой книги</p>
        <form method="post" id="createForm">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>

        </form>
      </div>
    </div>

  {% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/create_link.html
{% extends "base.html" %}
{% block title %}
  создать ссылку
{% endblock %}

  {% block content %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Укажите название и ссылку для новой книги</p>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {#form.as_p#}
          {% for field in form %}
            <p>{{field.label_tag}}</p>
          {% for error in field.errors %}
            {{error}}
          {% endfor %}
          <p>{{field}}</p>
          {% endfor %}
          <button type="submit" class="btn btn-primary">сохранить</button>
        </form>
      </div>
    </div>

  {% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/db.html
{% extends "base.html" %}
{% block title %}
    Управление базой данных
{% endblock %}

{% block content %}

    <div class="row">
    <h1>Управление базой данных</h1>
      <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
            <p>
                <a class="nav-link" href="{% url 'firstsite:cat_list' %}">Категории</a>
            </p>
            <p>
                <a class="nav-link" href="{% url 'firstsite:year_list' %}">Год издания</a>
            </p>
          </div>
      </div>
    </div>
{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/index.html
{% extends "base.html" %}
{% block title %}
{% endblock %}

{% block content %}

    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in books %}
          <div class="post-preview">
            <a href="{% url 'firstsite:book' id=item.id %}">
              <h1 class="post-title">
                {{ item.name }}
              </h1>
              <h2 class="post-subtitle">
                {{ item.category }}
              </h2>
            </a>
            <p class="post-meta">Posted by
              <a href="#">User</a>
              {{item.create}}</p>
          </div>
        {% endfor %}
        <hr>
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Next &rarr;</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/year_create.html
{% extends "base.html" %}
{% block title %}
{% endblock %}

  {% block content %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Укажите название элемента</p>
        <form method="post" id="createForm">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>

        </form>
      </div>
    </div>

  {% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/year_delete.html
{% extends "base.html" %}

{% block title %}
{{object.name}}
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        Удалить элемент "{{object.name}}"?
    </div>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
    </form>
</div>
{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/year_edit.html
{% extends "base.html" %}

{% block title %}
    Редактирование элемента
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

firstsite/firstsiteapp/templates/firstsiteapp/year_list.html
{% extends "base.html" %}
{% block title %}
    изменить элемент
{% endblock %}

{% block content %}

    <div class="row">
    <h1>Года издания</h1>
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in years %}
          <div>
            <b>  {{ item.name }} </b>
                <a href="{% url 'firstsite:year_edit' pk=item.pk %}">
                     &nbsp&nbsp&nbsp изменить &nbsp
                </a>
                <a href="{% url 'firstsite:year_delete' pk=item.pk %}">
                     &nbsp&nbsp&nbsp удалить &nbsp
                </a>
          </div>
        {% endfor %}
      </div>
    </div>


{% endblock %}